# fly.toml app configuration file generated for finance-redis on 2025-05-28T18:20:58-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'finance-redis'
primary_region = 'lax'

[build]
  image = 'redis:7-alpine'

[http_service]
  internal_port = 6379
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
