services:
  app:
    build: .
    container_name: financeApp
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}" # host:container
    depends_on:
      - db
      - cache
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: finance-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - financeApp-postgres-data:/var/lib/postgresql/data

  cache:                     
    image: redis:7-alpine
    container_name: financeApp-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  financeApp-postgres-data:
  redis-data: